Feature: JSON Message Schema validation
  This feature file validates json messages generated from Tealeaf SDK
  TestLink test cases are also covered here

# -- General Functionality test cases --
@type1
Scenario: checking type 1
  Given I am on the Welcome Screen
  #Then posted json should match the message type 1 schema
  Then posted json should match the client environment schema

@type2
Scenario: checking client environment, type 11, 4 and 5
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema

  When I touch TeaLeaf Sample App back button
  Then posted json should match the message type 2 schema

@type1145
Scenario: checking client environment, type 11, 4 and 5
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema

  When I touch Custom Event Button
  Then posted json should match the message type 5 schema

  And I touch textField1
  Then posted json should match the message type 4 schema

@type11
Scenario: checking client environment, type 11, 4 and 5
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema

@type4
Scenario: checking dwell, visitedCount properties in type 4
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema

  And I touch textField1
  Then posted json should match the message type 4 schema

  When I enter text in textField1
  #Then I touch Back Button
  Then posted json should match the message type 4 schema

  #When I enter text in textField1
  #Then posted json should match the message type 4 schema

@type10
Scenario: checking client environment, type 10
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I rotate device to right
  Then posted json should match the message type 10 schema

@type13
Scenario: checking client environment, type 13
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema

  When I touch Location Button
  Then posted json should match the message type 13 schema

@crash1
Scenario: checking type 6
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema
  And I touch App Crash Button
  Then posted json should match the message type 6 schema

@crash2
Scenario: checking type 6 cont
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  #When I select row 1 on home screen table
  Then posted json should match the message type 6 schema

# Set "RemoveIp": false in TealeafAdvancedConfig.json
@ipCapture
Scenario: Validating ip is captured as part of Client Environment
  Given I am on the Welcome Screen
  Then posted json should contain ip as part of client Environment

# Set "RemoveIp": true in TealeafAdvancedConfig.json
@ipMasking
Scenario: Validating ip is masked under Client Environment
  Given I am on the Welcome Screen
  Then posted json should not contain ip as part of client Environment

# Set TealeafBasicConfig.plist: GetImageDataOnScreenLayout = YES
@imageLogging
Scenario: validating device specific items - camera
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 6 on home screen table
  #Then posted json should have type 10 and contains image property
  #Then posted json should match the message type 11 schema

  Then I touch Get Photo button
  #Then posted json should have type 10 and contains image property
  #Then posted json should match the client environment schema

  Then I touch Post to Server button
  #Then posted json should have type 10 and contains image property
	Then Image is posted to the server

@UnresponsiveTarget
Scenario: iOS SDK with default configuration behavior when dealing with an unresponsive target page
  Given I am on the Welcome Screen
  Then I don't see any logs
  #Then I select row 1 on home screen table

@Sessionization
Scenario: Validate sessionization on any one of the iOS
  Given I am on the Welcome Screen
  Then posted json should have EOCoreSessionID in the json log

@CapturingLostHits1
Scenario: UI hits generated by the Tealeaf SDK should not be sent to server
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  Then I select row 1 on home screen table
  Then I close the app

@CapturingLostHits2
Scenario: Lost hits should be captured now
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  Then posted json should match the message type 11 schema

# -- Validate ease of use test cases --

@AppendMapIds
Scenario: AppendMapIds in TealeafLayoutConfig.json
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should have message type 10 and contains custom id for textView

@AutoLayout10
Scenario: functional - easy of use - AutoLayout support type 10
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  When I select row 1 on home screen table
  Then posted json should have message type 10 and contains "Banana" under layout

  #When I select row 1 on home screen table
  #Then posted json should have message type 10 and contains "_Peggy" in type4 click

# -- Validate Configuration test cases --

@EnableTLF
Scenario: TLF is enabled
  When I am on the Welcome Screen
  Then TLF is enabled

@DisableTLF
Scenario: TLF is disabled
  When I am on the Welcome Screen
  Then TLF is disabled

@killSwitch1
Scenario: validating configuration item - killswitch is enabled and reachable
  When I am on the Welcome Screen
  Then TLF is enabled

@killSwitch2
Scenario: validating configuration item - killswitch is enabled and unreachable
  When I am on the Welcome Screen
  Then TLF is disabled

@logLayout1
Scenario: Validating configuration item - logLayout&Image Setting: I disable gesture detector and native gestures capture on webView
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  When I select row 1 on home screen table
  Then posted json should not have type 11 and fromWeb property is set to false

@logLayout2
Scenario: Validating configuration item - logLayout&Image Setting: I disable native gestures capture on webView
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  When I select row 1 on home screen table
  Then posted json should have type 11 and fromWeb property is set to false

@logLayout3
Scenario: Validating configuration item - logLayout&Image Setting: I enable gesture detector and native gestures capture on webView
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  When I select row 1 on home screen table
  Then posted json should have type 11 and fromWeb property is set to true

@TextFieldMasking
Scenario: validating configuration item - masking case 3
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema

  When I touch textField1
  Then posted json should match the message type 4 schema

  When I enter text in textField1
  Then textField is secure and logging level is 3

# -- Gestures -- Test cases --
@Gesture1
Scenario: validating gesture’s tlType 1
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  And I select row 5 on home screen table
  Then posted json should match the message type 11 schema

  #And I tap view 1
  #Then posted json should match the message type 11 schema

  #And I swipe left on "swipeView"
  And I left swipe view 2
  Then posted json should match the message type 11 schema

  #Then I pinch to zoom in on "pinchView"
  #And I pinch view 3
  #Then posted json should match the message type 11 schema

@Gesture2
Scenario: Validation gesture's tlType 2
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema
  And I select row 5 on home screen table
  Then posted json should match the message type 11 schema

  #And I swipe right on "swipeView"
  And I right swipe view 2
  Then posted json should match the message type 11 schema

@visitedCount
Scenario: Validation gesture's tlType 2
  Given I am on the Welcome Screen
  Then posted json should match the client environment schema

  When I select row 1 on home screen table
  Then posted json should match the message type 11 schema

  And I enter text in textField1
  Then posted json should match the message type 4 schema
